### PR TITLE
Android: Data messages and more styles

### PR DESCRIPTION
**Pull request by m1ga**
screenshot_1532191339456

* Data messages (not handled by the system but by the app with custom options)
* support for big text (summary, text)
* big image (big remote image below the message)
* icon (remote image next to the message)
* more data push options:  title, message, big_text, big_text_summary, icon, image, force_show_in_foreground, id

Used many parts of [ti.goosh](https://github.com/caffeinalab/ti.goosh) (thanks @caffeinalab and all contributors) so users can switch more easily. 

[Test binary](https://migaweb.de/firebase.cloudmessaging-android-1.2.0.zip)

Tests:
* [x] data message
* [x] notification message
* [x] big text
* [x] big image
* [x] icon
* [x] colored title
* [x] foreground / background / killed
* [x] hidden notification (foreground / background / killed)
* [x] get data at app start

### CODE REVIEW

**Comment by m1ga** [comment]
ti.goosh has some more options: https://github.com/caffeinalab/ti.goosh#send-the-notification-from-your-server like color, lights, vibrate,... which would be useful too

**Comment by R4mpancy** [comment]
I'm currently wrapping up a push notification system for my apps. I doubt I'd be able to work it into this upcoming release but I would love to see & use this feature in the future. It would definitely add more value to the apps.

Let me know if there's anything I could do to help.

**Comment by R4mpancy** [comment]
Hey @m1ga  I've taken some time today to download that binary and get it into my project without much success however. To be clear, those extra parameters you exposed should be passed along into the data array right?

**Comment by m1ga** [comment]
the new fields will be in the data node, yes. I'll do an update at the weekend since it currently has some debug stuff inside. But I'm pretty happy with the current status and it should be stable real soon. The there will be a full example and some documentation, too!
I think the only part that is not working (and I'm not sure how it could) is a hidden push when the app is killed (so no notification by the system). I don't get the data into the app.

**Comment by R4mpancy** [comment]
Hmm, I haven't gotten a successful example yet using any of the new fields. Is there a way at run-time to make sure that I'm using the correct version of the module? I've specified the version 1.2.0 in the tiapp.xml
I'd like to help in the testing if I can

**Comment by m1ga** [comment]
I've updated the module. This is my PHP script I'm using to test the features:

test.php
```php
<?php $url = 'https://fcm.googleapis.com/fcm/send';

	$fields = array (
			'to' => "",
			'data' => array(
				 "test1" => "value1",
				 "test2" => "value2",
				"timestamp"=>date('Y-m-d G:i:s'),
				 "title" => "title",
				"message" => "message",
				"big_text"=>"big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text big text even more text ",
				"big_text_summary"=>"big_text_summary",
				"icon" => "http://via.placeholder.com/350x150",
				"image" => "http://via.placeholder.com/350x150",
				"force_show_in_foreground"=> true,
				"color" => "#ff6600"
			)
	);

	$headers = array (
			'Authorization: key=key',
			'Content-Type: application/json'
	);

	$ch = curl_init ();
	curl_setopt ( $ch, CURLOPT_URL, $url );
	curl_setopt ( $ch, CURLOPT_POST, true );
	curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
	curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
	curl_setopt ( $ch, CURLOPT_POSTFIELDS, json_encode($fields));

	$result = curl_exec ( $ch );
	echo $result."\n";
	curl_close ( $ch );
?>
```

`php test.php`

screenshot_20180825-124053

(if using the big image it won't show the big text, but it is transmitted)

**Comment by m1ga** [comment]
@R4mpancy if you can please test the updated binary in the first post!
Latest readme: https://github.com/hansemannn/titanium-firebase-cloud-messaging/blob/100738d98288c56693dcaa6ae743aa98ef33029d/README.md

**Comment by R4mpancy** [comment]
I was able to successfully test all the new data attributes on a Galaxy S7 emulator running Android Nougat (7.0) however have ran into issues using my Nexus 5X running Oreo (8.1) and Pixel 2 running P (9). Specifically get a developer warning that the app is trying to use a "null" notification channel.

Is there a way to specify in the data field or from the server which notification channel to hit?

**Comment by R4mpancy** [comment]
Yes I did, but I didn't in the previous version of this module so there's a prior 'Miscellaneous' channel that was created by default on those devices. Don't know if that would cause a problem or not.

**Comment by m1ga** [comment]
@hansemannn I think we are ready to merge here. Updated the README so there are no conflicts. You can use it like before but you have some new options for Android (examples in the new documentation)

**Comment by hansemannn** [comment]
Released via https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.2.0

**Pull request merged**
